services:
  ibrows.codebaseapi.store.shortcut:
    class: %ibrows_codebaseapi.store.shortcut.class%
    arguments: [%ibrows_codebaseapi.store.shortcut.path%]
    
  ibrows.codebaseapi.store.credential:
    class: %ibrows_codebaseapi.store.credential.class%
    arguments: [%ibrows_codebaseapi.store.credential.path%]
    
  ibrows.codebaseapi.encryption:
    class: %ibrows_codebaseapi.encryption.class%
    arguments: [%ibrows_codebaseapi.encryption.cypher%, %ibrows_codebaseapi.encryption.mode%, %ibrows_codebaseapi.encryption.iv_mode%]
    
  ibrows.codebaseapi.storeandecryption.credential:
    class: %ibrows_codebaseapi.store_and_encryption.class%
    arguments: [@ibrows.codebaseapi.store.credential, @ibrows.codebaseapi.encryption]
    
  ibrows.codebaseapi.storeandecryption.shortcut:
    class: %Ibrows\CodebaseApi\StoreAndEcryption\StoreAndEncryption
    arguments: [@ibrows.codebaseapi.store.shortcut, @ibrows.codebaseapi.encryption]
  
  ibrows.codebaseapi.result.factory:
    class: Ibrows\CodebaseApi\Result\ResultFactory
    arguments: [%ibrows_codebaseapi.result.factory.type%]
  
  ibrows.codebaseapi.transport.factory:
    class: Ibrows\CodebaseApi\Transport\TransportFactory
    arguments: [%ibrows_codebaseapi.uri%, @ibrows.codebaseapi.result.factory]